apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  name: ${NAME}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ${NAME}:latest
  postCommit:
    script: npm test
  source:
    contextDir: ${CONTEXT_DIR}
    git:
      ref: ${SOURCE_REPOSITORY_REF}
      uri: ${SOURCE_REPOSITORY_URL}
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: NPM_MIRROR
          value: ${NPM_MIRROR}
      from:
        kind: ImageStreamTag
        name: nodejs:4
        namespace: ${NAMESPACE}
    type: Source
  triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic