stage('Build') {
  step() {
  printf(
  "pull changes"
  )
  checkout
  scm
}
step() {
  printf(
  "run build"
  )
  sh
  'mvn build -skipTests'
}
}

stage('Test') {
  step() {
    printf("run unit tests")
    sh 'mvn test'
  }
}
stage('Deploy') {
  step() {
   openshiftDeploy(deploymentConfig: '${APPLICATION_NAME}')
  }
}


//  steps {
//  echo
//  'Building..'
//}

//steps {
//echo 'Testing..'
//sh 'mvn test'
//}


//stage('Deploy Application') {
//steps {
//script {
//openshift.withCluster() {
//openshift.withProject() {
//openshiftDeploy(deploymentConfig: '${APPLICATION_NAME}')
//}
//}
//}
//}
//}